"""Add TTL to nameserver.

Revision ID: 4fa78fdd3f74
Revises: b780f60b3019
Create Date: 2020-11-18 16:55:35.514517

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '4fa78fdd3f74'
down_revision = 'b780f60b3019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dns_nameservers', sa.Column('ttl', sa.Integer(), nullable=True))
    op.execute('UPDATE dns_nameservers SET ttl = 30')
    op.alter_column('dns_nameservers', 'ttl', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dns_nameservers', 'ttl')
    # ### end Alembic commands ###
