name: build-server

on:
  push:
    branches: trunk
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build image job
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              env:
                DOCKER_USER: ${{ secrets.DOCKER_USER }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              with:
                publish: true
                imageName: fergalmoran/bitchmin-api
                dockerFile: ./server/Dockerfile
                buildArg: ./server
                platform: linux/arm/v7
                dockerHubUser: ${{DOCKER_USER}}
                dockerHubPassword: ${{DOCKER_PASSWORD}}