name: build-server

on:
  push:
    branches: trunk
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Show credentials
        run: echo ${{ secrets.DOCKER_USERNAME }}
             echo ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${ secrets.DOCKER_USERNAME }}
          password: ${ secrets.DOCKER_PASSWORD }}          
      -
        name: Run Buildx
        if: success() && github.event_name != 'pull_request'        
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --output "type=image,push=true" \
            -t fergalmoran/bitchmin-api \
            --file ./server/Dockerfile ./server